### PR TITLE
Create pksim5_untrack.cmd

### PR DESCRIPTION
**Pull request by abdelr**

### CODE REVIEW

**Comment by msevestre** [comment]
@abdelr build-scripts are used by every project and therefor should not contain project specific stuff (to be consistent with what we have)
Can you move those scripts to PKSim itself? 
I am also not quite sure what this is doing. Who is supposed to call those scripts and when? The issue only occurs when running integration tests locally

**Comment by abdelr** [comment]
@msevestre You are right, this script is specific for PKSim right now. Maybe it could be more general later if we need it on other projects. Actually it is more like a draft right now. The scripts manipulate the index changing the bits to ensure whether the files are to be committed or not. 
The only thing here is what will happen when we actually change the config files. Then it will need some little manual work but that is all. 
These scripts are intended for the user to run the untrack version when first clone. This way, git will actually trust we do not want to commit ever any change on them. If at some point we do need, we then double click the retrack version. This could also be extended to any other file in the same situation.

From documentation [https://git-scm.com/docs/git-update-index]:
--[no-]assume-unchanged
When this flag is specified, the object names recorded for the paths are not updated. Instead, this option sets/unsets the "assume unchanged" bit for the paths. When the "assume unchanged" bit is on, the user promises not to change the file and allows Git to assume that the working tree file matches what is recorded in the index. If you want to change the working tree file, you need to unset the bit to tell Git. This is sometimes helpful when working with a big project on a filesystem that has very slow lstat(2) system call (e.g. cifs).

Git will fail (gracefully) in case it needs to modify this file in the index e.g. when merging in a commit; thus, in case the assumed-untracked file is changed upstream, you will need to handle the situation manually.

**Comment by msevestre** [comment]
@abdelr Still, I don't think this script as is belongs in our build-scripts. They will be also very hard to find because they are not saved at the root of the project

In short the idea is

1/CLone pksim
2/Run the script

In PKSim, we have a place to run scripts local to the project. see rakefile.rb (it's rake but you can call the same type of stuff as a bat file using a command line syntax)

What happens if you want to add a new pksim5 project to source code. What is the flow in that case? 
1/Track 
2/add
3/untrack?

**Comment by abdelr** [comment]
@msevestre I agree it should not go here. I am not sure whether we should move it to another place or completely remove it though. I am proposing to use it but I will only move it when we decide this is the solution we will use.

Indeed, the idea is to clone pksim, then run the script. I thought about git hooks but there is no after clone. We could have some after pull hook for example but it will only be necessary after cloning. Although, now that you mention it, if we add a new pksim5 file, the file will need to be marked as well meaning you will need to run the script again. Maybe it is not a bad idea to use an after pull hook to run the script.

In case you create a new pksim5 file, you will not need to do anything special for adding it to the repo. The script will explore the folder for *.pksim5 and mark all existing files so your newly created file is not marked yet (as it did not exist when the script was run). After committing it everyone will need to rerun the script though. The only need for retrack script is in case you need to modify an existing pksim5 file. You would need to track changes on it again and then commit the changes. After you finish adding the file I would recommend running the untrack again.

**Comment by msevestre** [comment]
@abdelr Let's discuss this with Juri and you can explain. Hard for me to understand how this is easier that not committing the files at the first place when it was changed. I am hardly ever running the integrationstest on my machine so this issue never occurs to me.

**Comment by Yuri05** [comment]
@abdelr @msevestre This PR is open since 4 months. Should we close it?

**Comment by msevestre** [comment]
it says let's discuss with @Yuri05 :) I don't remember why this change was suggested in the first place. Maybe we can talk about it on wed?

**Comment by Yuri05** [comment]
Anything new here? Can we either merge or close this PR? 
(not sure why we need those scripts, but they are PK-Sim specific and not generic, so prob. this Repo is not the right place anyway)

**Comment by msevestre** [comment]
Closing

**Pull request closed without merging**
